[package]
name = "postgres-datetime"
authors = ["Petros Angelatos <petrosagg@gmail.com>"]
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
libc= "0.2"
bitmask = "0.5"
once_cell = "1"

[dev-dependencies]
datadriven = "0.6"
